#!/usr/bin/env bash
# A Bash script that transfers a file from Holberton's client to a server
if [$# < 3]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/$1
