#!/usr/bin/env bash
# Script to install nginx and send a GET request using curl
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
