#!/usr/bin/env bash
# Installing and configuring the HAProxy
ufw allow 1344
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
fe="frontend main\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\n"
be="backend web_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 4910-web-01 3.92.32.198:80 check\n\tserver 4910-web-02 18.234.64.16:80 check\n"
echo -e "\n\n""$fe""$be" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
