#!/usr/bin/env bash
# Setting up a firewall with rules.
sudo apt update -y
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
